### PR TITLE
Added new EFCore NoChangeTrackingCompiledQueryBencher

### LINKED ISSUE #65: Add EF Core NoChangeTracking with CompiledQuery Bencher
Add a new bencher for EF Core NonChange tracking with CompiledQuery to test what performance improvement CompileQuery will give.

### PR DESCRIPTION
**Pull request by jonnybee**
Closes #65

### CODE REVIEW

**Comment by FransBouma** [comment]
Can't test pull this for some messed up reason on teh command line, so merging it and then testing...

**Comment by FransBouma** [comment]
Interestingly enough, it's slower, see results :) https://github.com/FransBouma/RawDataAccessBencher/blob/master/Results/20220801_net6.txt

**Comment by jonnybee** [comment]
Maybe not so surprising on the  set fetches as the query has no parameters. I would expect to see more improvements if there was a complex expression tree in the query. 

On the non-changetracking individual fetches it is a good improvement: 
| Non-change tracking individual fetches (100 elements, 10 runs), no caching |                                                |
|----------------------------------------------------------------|------------------------------------------------|
| Entity Framework Core CompiledQuery v6.0.7.0 (v6.0.722.31501)                |  0,15ms (0,14ms) per individual fetch |
| Entity Framework Core v6.0.7.0 (v6.0.722.31501)   |  0,23ms (0,12ms) per individual fetch  |


| Memory usage, per individual element |                                                |
|----------------------------------------------------------------|------------------------------------------------|
| Entity Framework Core CompiledQuery v6.0.7.0 (v6.0.722.31501)                |  11 KB (11.552 bytes) |
| Entity Framework Core v6.0.7.0 (v6.0.722.31501)   |  18 KB (18.664 bytes)  |

**Comment by FransBouma** [comment]
True, I looked at the set fetches :X 👍

**Pull request merged**
