### PR TITLE
#55 update benchers ef6 ef core peta poco

### PR DESCRIPTION
**Pull request by jonnybee**
Upgraded projects and benchers:
* use new project format with minimum references to NuGet packages 
* use only NET4.8, NET5.0, netstandard2.0 and netstandard2.1 as target frameworks 
* make EF6 assemblies multitarget netstandard2.0 and netstandard 2.1 
* make EF Core assemblies multitarget and use EF Core 3.1.16 on netstandard 2,0 and EF Core 5.0.7 on netstandard 2,1
* rune EF6 and EF Core benchers on both .NET 4.8 and .NET 5.0 
* upgraded to latest version of Dapper 
* upgraded to latest version of PetaPoco.Compiled (v6)
* added System.Configuraton.ConfigurationManger package to RawBencher.Core and use ConfigurationManager for all connection strings in both benchers projects. 
* changed NHibernate projects to new project format and target netstandard2.0 
* upgraded to latest version of NHibernate and added NHibernate reference and tests to RawBencher.Core
* updated requirements in readme.md

Developers may need to manually delete existeing bin and obj folders to compile solution or clean the workspace in GIT.

### CODE REVIEW

**Comment by FransBouma** [comment]
I can't get the damn RawBencher project to compile. Every mscorlib type is unknown. VS thinks it should obtain the mscorlib dll from the bin folder. why is beyond me

**Comment by FransBouma** [comment]
The RawBencher.csproj is messed up. I'll try to revert it with the original one, as the one in your pr is broken here I removed all bin/obj files, and what not. No idea wtf is wrong with the tooling that this goes wrong

**Comment by jonnybee** [comment]
I had to delete all bin and obj folders in the projects to get it to build.

VS store some generated. Jason files in obj folders that must be deleted.

Best regards
Jonny Bekkum

**Comment by jonnybee** [comment]
Do you get error on Microsoft. Code Analysis. Analyzers.dll?

I cleaned the solution and now get this error. I can dig into it.

Best regards
Jonny Bekkum

**Comment by FransBouma** [comment]
I constructed the old csproj back, which is the old format. Now it compiles. The only error I now get is a version conflict with json.net, which is likely some nuget package reference somewhere. 

Removing the bin/obj folders is something I did, actually. Clean solution also does that, but it shouldn't be necessary. I don't get the error on the analyzer dll, but I think we can remove that one. I'll remove it (I'm currently looking at your PR code so I'll fix things in there, then merge the PR)

**Comment by jonnybee** [comment]
I removed these lines from new csproj:
Snippet

  <Import Project="..\packages\Microsoft.CodeAnalysis.Analyzers.3.3.0\build\Microsoft.CodeAnalysis.Analyzers.props"
Condition="Exists('..\packages\Microsoft.CodeAnalysis.Analyzers.3.3.0\build\Microsoft.CodeAnalysis.Analyzers.props')"
/>

  <ItemGroup>    <Analyzer
Include="..\packages\Microsoft.CodeAnalysis.Analyzers.3.3.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.Analyzers.dll"
/>    <Analyzer
Include="..\packages\Microsoft.CodeAnalysis.Analyzers.3.3.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll"
/>  </ItemGroup>


And project builds fine now here.

best regards

Jonny


tir. 15. jun. 2021 kl. 11:19 skrev Frans Bouma ***@***.***>:

**Comment by jonnybee** [comment]
Hi Frans,

Sorry about the issues with RawBencer project.,

I have updated my PR source with edits in the converted csproj file.

best regards
Jonny Bekkum

tir. 15. jun. 2021 kl. 11:22 skrev Jonny Bekkum ***@***.***>:

**Comment by FransBouma** [comment]
That wasn't necessary. I have a working version or your PR locally now, I'll merge it in a minute.

**Comment by FransBouma** [comment]
I think the problem with the csproj is something local anyway. So it now works again :)

**Comment by FransBouma** [comment]
Manually merged

**Comment by FransBouma** [comment]
Will now update the packages / generated code of some frameworks. then re-run the benches

**Comment by FransBouma** [comment]
All good. Have posted new results in: https://github.com/FransBouma/RawDataAccessBencher/tree/master/Results

Thanks for the hard work, Jonny! :)

**Pull request closed without merging**
