### PR TITLE
Update Dapper to NuGet 1.42 release rather than static file

### PR DESCRIPTION
**Pull request by mgravell**
Update Dapper to NuGet 1.42 release rather than static file; tweak to avoid some unnecessary list allocations

### CODE REVIEW

**Comment by FransBouma** [comment]
Thanks! Will have a look at it in the morning!

**Comment by mgravell** [comment]
Note: I had problems building out-of-the-box due to Telerik.Bencher.Model not wanting to build, which meant I had to hack around it in my local and then fake the csproj edits for the commit.

Note 2: it isn't expected for this to improve the dapper score; it may even be slightly slower due to additional features having been added over time

**Comment by FransBouma** [comment]
Yeah the telerik shit is annoying. I'll remove that one, as they have been annoying since day one of their existence (as Vanatec Open Access, using 'LLBLGen' as keyword at google and other sillyness). The code has to build, if their stuff is causing a failed build, they're out.

Will merge locally and fix up the telerik stuff and push. 

(spaces instead of tabs? ;))

**Comment by FransBouma** [comment]
It's not that bad. 

```
Averaged total results per framework. Fastest and slowest result omited
==============================================================================
Non-change tracking fetches, set fetches (10 runs), no caching
------------------------------------------------------------------------------
Handcoded materializer using DbDataReader                                : 118,50ms.    Enumeration average: 1,00ms
Handcoded materializer using DbDataReader with GetValues(array) (boxing) : 120,50ms.    Enumeration average: 1,00ms
PetaPoco Fast v4.0.3                                                     : 145,00ms.    Enumeration average: 1,00ms
PetaPoco v4.0.3                                                          : 150,50ms.    Enumeration average: 1,00ms
Dapper 1.40.0.0                                                          : 170,50ms.    Enumeration average: 1,00ms
Entity Framework v6.0.0.0 (v6.1.31219.0)                                 : 176,75ms.    Enumeration average: 1,00ms
Linq to Sql v4.0.0.0 (v4.6.81.0)                                         : 182,50ms.    Enumeration average: 1,00ms
LLBLGen Pro v4.2.0.0 (v4.2.15.0127), Poco typed view with QuerySpec      : 252,38ms.    Enumeration average: 0,13ms
ServiceStack OrmLite v4.0.36.0 (v4.0.36.0)                               : 257,75ms.    Enumeration average: 1,00ms
LLBLGen Pro v4.2.0.0 (v4.2.15.0127), Poco typed view with Linq           : 262,38ms.    Enumeration average: 0,00ms
LLBLGen Pro v4.2.0.0 (v4.2.15.0127), typed view                          : 295,13ms.    Enumeration average: 3,13ms
Massive using dynamic class                                              : 447,13ms.    Enumeration average: 18,00ms
Oak.DynamicDb using dynamic Dto class                                    : 526,25ms.    Enumeration average: 80,25ms

Change tracking fetches, set fetches (10 runs), no caching
------------------------------------------------------------------------------
DataTable, using DbDataAdapter                                           : 185,88ms.    Enumeration average: 26,75ms
Linq to Sql v4.0.0.0 (v4.6.81.0)                                         : 243,25ms.    Enumeration average: 1,00ms
LLBLGen Pro v4.2.0.0 (v4.2.15.0127)                                      : 254,13ms.    Enumeration average: 3,00ms
Oak.DynamicDb using typed dynamic class                                  : 504,63ms.    Enumeration average: 598,75ms
NHibernate v3.3.1.4000 (v3.3.3.4001)                                     : 1.578,50ms.  Enumeration average: 1,00ms
Entity Framework v6.0.0.0 (v6.1.31219.0)                                 : 1.767,38ms.  Enumeration average: 1,25ms

Non-change tracking individual fetches (100 elements, 10 runs), no caching
------------------------------------------------------------------------------
Handcoded materializer using DbDataReader with GetValues(array) (boxing) : 0,51ms per individual fetch
Handcoded materializer using DbDataReader                                : 0,52ms per individual fetch
Massive using dynamic class                                              : 0,55ms per individual fetch
Oak.DynamicDb using dynamic Dto class                                    : 0,58ms per individual fetch
ServiceStack OrmLite v4.0.36.0 (v4.0.36.0)                               : 0,60ms per individual fetch
LLBLGen Pro v4.2.0.0 (v4.2.15.0127), Poco typed view with QuerySpec      : 0,67ms per individual fetch
PetaPoco Fast v4.0.3                                                     : 0,71ms per individual fetch
LLBLGen Pro v4.2.0.0 (v4.2.15.0127), typed view                          : 0,73ms per individual fetch
Entity Framework v6.0.0.0 (v6.1.31219.0)                                 : 0,79ms per individual fetch
Dapper 1.40.0.0                                                          : 1,06ms per individual fetch
LLBLGen Pro v4.2.0.0 (v4.2.15.0127), Poco typed view with Linq           : 1,39ms per individual fetch
Linq to Sql v4.0.0.0 (v4.6.81.0)                                         : 1,45ms per individual fetch
PetaPoco v4.0.3                                                          : 2,06ms per individual fetch

Change tracking individual fetches (100 elements, 10 runs), no caching
------------------------------------------------------------------------------
Oak.DynamicDb using typed dynamic class                                  : 0,56ms per individual fetch
DataTable, using DbDataAdapter                                           : 0,56ms per individual fetch
LLBLGen Pro v4.2.0.0 (v4.2.15.0127)                                      : 0,59ms per individual fetch
NHibernate v3.3.1.4000 (v3.3.3.4001)                                     : 0,66ms per individual fetch
Entity Framework v6.0.0.0 (v6.1.31219.0)                                 : 0,84ms per individual fetch
Linq to Sql v4.0.0.0 (v4.6.81.0)                                         : 1,49ms per individual fetch

Change tracking fetches, set fetches (10 runs), caching
------------------------------------------------------------------------------
LLBLGen Pro v4.2.0.0 (v4.2.15.0127)                                      : 74,75ms.     Enumeration average: 3,00ms

Change tracking individual fetches (100 elements, 10 runs), caching
------------------------------------------------------------------------------
LLBLGen Pro v4.2.0.0 (v4.2.15.0127)                                      : 0,11ms per individual fetch
```

**Comment by FransBouma** [comment]
last one

```
Averaged total results per framework. Fastest and slowest result omited
==============================================================================
Non-change tracking fetches, set fetches (10 runs), no caching
------------------------------------------------------------------------------
Handcoded materializer using DbDataReader                                : 148,13ms.    Enumeration average: 1,00ms
Handcoded materializer using DbDataReader with GetValues(array) (boxing) : 162,25ms.    Enumeration average: 1,00ms
PetaPoco Fast v4.0.3                                                     : 167,63ms.    Enumeration average: 1,00ms
PetaPoco v4.0.3                                                          : 186,00ms.    Enumeration average: 1,00ms
Dapper 1.40.0.0                                                          : 195,50ms.    Enumeration average: 1,00ms
Entity Framework v6.0.0.0 (v6.1.40302.0)                                 : 205,25ms.    Enumeration average: 1,00ms
Linq to Sql v4.0.0.0 (v4.6.81.0)                                         : 208,13ms.    Enumeration average: 1,00ms
LLBLGen Pro v4.2.0.0 (v4.2.15.1015), Poco typed view with QuerySpec      : 262,50ms.    Enumeration average: 1,00ms
LLBLGen Pro v4.2.0.0 (v4.2.15.1015), Poco typed view with Linq           : 311,25ms.    Enumeration average: 0,50ms
LLBLGen Pro v4.2.0.0 (v4.2.15.1015), typed view                          : 315,00ms.    Enumeration average: 3,75ms
ServiceStack OrmLite v4.0.46.0 (v4.0.46.0)                               : 334,13ms.    Enumeration average: 1,00ms
Massive using dynamic class                                              : 480,88ms.    Enumeration average: 11,38ms
Oak.DynamicDb using dynamic Dto class                                    : 570,75ms.    Enumeration average: 82,38ms

Change tracking fetches, set fetches (10 runs), no caching
------------------------------------------------------------------------------
DataTable, using DbDataAdapter                                           : 205,13ms.    Enumeration average: 27,63ms
Linq to Sql v4.0.0.0 (v4.6.81.0)                                         : 275,25ms.    Enumeration average: 1,00ms
LLBLGen Pro v4.2.0.0 (v4.2.15.1015)                                      : 315,50ms.    Enumeration average: 3,25ms
Oak.DynamicDb using typed dynamic class                                  : 580,50ms.    Enumeration average: 599,88ms
NHibernate v4.0.0.4000 (v4.0.4.4000)                                     : 1.861,38ms.  Enumeration average: 1,00ms
Entity Framework v6.0.0.0 (v6.1.40302.0)                                 : 2.051,00ms.  Enumeration average: 2,00ms

Non-change tracking individual fetches (100 elements, 10 runs), no caching
------------------------------------------------------------------------------
Handcoded materializer using DbDataReader                                : 0,49ms per individual fetch
Handcoded materializer using DbDataReader with GetValues(array) (boxing) : 0,50ms per individual fetch
Massive using dynamic class                                              : 0,51ms per individual fetch
Oak.DynamicDb using dynamic Dto class                                    : 0,54ms per individual fetch
ServiceStack OrmLite v4.0.46.0 (v4.0.46.0)                               : 0,56ms per individual fetch
LLBLGen Pro v4.2.0.0 (v4.2.15.1015), Poco typed view with QuerySpec      : 0,65ms per individual fetch
PetaPoco Fast v4.0.3                                                     : 0,66ms per individual fetch
LLBLGen Pro v4.2.0.0 (v4.2.15.1015), typed view                          : 0,73ms per individual fetch
Entity Framework v6.0.0.0 (v6.1.40302.0)                                 : 0,78ms per individual fetch
Dapper 1.40.0.0                                                          : 0,96ms per individual fetch
LLBLGen Pro v4.2.0.0 (v4.2.15.1015), Poco typed view with Linq           : 1,37ms per individual fetch
Linq to Sql v4.0.0.0 (v4.6.81.0)                                         : 1,43ms per individual fetch
PetaPoco v4.0.3                                                          : 2,08ms per individual fetch

Change tracking individual fetches (100 elements, 10 runs), no caching
------------------------------------------------------------------------------
DataTable, using DbDataAdapter                                           : 0,55ms per individual fetch
Oak.DynamicDb using typed dynamic class                                  : 0,56ms per individual fetch
LLBLGen Pro v4.2.0.0 (v4.2.15.1015)                                      : 0,56ms per individual fetch
NHibernate v4.0.0.4000 (v4.0.4.4000)                                     : 0,65ms per individual fetch
Entity Framework v6.0.0.0 (v6.1.40302.0)                                 : 0,86ms per individual fetch
Linq to Sql v4.0.0.0 (v4.6.81.0)                                         : 1,46ms per individual fetch

Change tracking fetches, set fetches (10 runs), caching
------------------------------------------------------------------------------
LLBLGen Pro v4.2.0.0 (v4.2.15.1015)                                      : 77,00ms.     Enumeration average: 3,63ms

Change tracking individual fetches (100 elements, 10 runs), caching
------------------------------------------------------------------------------
LLBLGen Pro v4.2.0.0 (v4.2.15.1015)                                      : 0,12ms per individual fetch
```

EF and NH lost serious performance in their latest versions. Interesting :)

**Comment by mgravell** [comment]
I don't think anyone at MS is going to try to fix EF6 at this point, but I
have a hunch they're working very very hard on perf for EF7

**Comment by mgravell** [comment]
Question: any objection if I add a PR with a core-clr build? Limited to
core-clr compliant tooling, obviously.

**Comment by FransBouma** [comment]
re: core clr build: sure. I haven't build anything against that yet so if you can add that, that would be great!

re: perf in EF, yeah for EF6 it is too cumbersome to fix the performance problems, it's highly over-engineered. I profiled it a lot to see where the performance loss was located, and whether I did something stupid or not, but it's really lost in a lot of overhead. Same for NHibernate. EF7 might be faster, but then again, it's at the moment nothing more than what L2S brings to the table, so if they're slower than L2S, IMHO they have actually not accomplished what they wanted. 

I've forked L2S code, and am planning to port it to core clr in the near future (but that will be next year I think. First I have to finish v5 of llblgen)

**Pull request merged**
