### PR TITLE
Use a pooledDbContextFactoryw with EF Core

### LINKED ISSUE #59: EF Core should use a PooledDbContextFactory

### PR DESCRIPTION
**Pull request by ErikEJ**
fixes #59

### CODE REVIEW

**Comment by FransBouma** [comment]
What does a pooled db context factory do exactly? Does it keep the connection open for instance? As that's not allowed for this benchmark. If it caches the meta-data / proxy classes, it's ok

**Comment by ErikEJ** [comment]
It caches the Internal model, not connections https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#dbcontext-pooling

**Comment by mikependon** [comment]
The performance and efficiency impact is quite high when this setting is enabled as per the documentation.

image

> For these cases, EF Core can pool your context instances: when you dispose your context, EF Core resets its state and stores it in an internal pool; when a new instance is next requested, that pooled instance is returned instead of setting up a new one. Context pooling allows you to pay context setup costs only once at program startup, rather than continuously.

What happened to the already in used connection object when the EF Core reset its state and stores back to the pool? Also, what does context setup only happening once during startup?

**Comment by ErikEJ** [comment]
@mikependon AFAIK, DbContext does not store any connection objects. Connection pooling is managed by the ADO.NET provider.

**Comment by FransBouma** [comment]
I doubt it has a lot of impact in this particular benchmark, but we'll see. If it doesn't keep an open connection around, it's similar to the context factory of nhibernate, which basically hands out a new, but cached session object with shared meta-data.

**Comment by ErikEJ** [comment]
Looking forward...

**Comment by FransBouma** [comment]
I first updated all frameworks to their latest official releases, then ran a run pre-merge: 
https://github.com/FransBouma/RawDataAccessBencher/blob/master/Results/20220722_net6_1.txt

I then merged, did a full build and ran another run:
https://github.com/FransBouma/RawDataAccessBencher/blob/master/Results/20220722_net6_2.txt

As you can see it has little, if any, influence on this benchmark. While I expected no influence in the set fetches, it surprises me a bit it didn't have any influence in the individual fetches nor memory consumption. Did you see a different result locally, @ErikEJ ?

**Comment by ErikEJ** [comment]
Actually for "Non-change tracking individual fetches (100 elements, 10 runs)", I see good improvements, but maybe I am reading it wrong?

1.txt: 

`Entity Framework Core v6.0.7.0 (v6.0.722.31501)                       : 0,31ms (0,01ms) per individual fetch`

`Entity Framework Core v6.0.7.0 (v6.0.722.31501)                       : 99 KB (102.016 bytes)`
(and second slowest)

2.txt:

`Entity Framework Core v6.0.7.0 (v6.0.722.31501)                       : 0,13ms (0,01ms) per individual fetch`

`Entity Framework Core v6.0.7.0 (v6.0.722.31501)                       : 19 KB (19.544 bytes)`

**Comment by FransBouma** [comment]
Oh you're right, I looked at the wrong row :D! that's indeed a good improvement 👍

**Pull request merged**
