### PR TITLE
Updates and fixes for Tortuga Chain

### PR DESCRIPTION
**Pull request by Grauenwolf**
Fixed bug in RawBencher that was breaking Chain Compiled
Added Chain Compiled to .NET Core
Added other Chain materializers

### CODE REVIEW

**Comment by FransBouma** [comment]
What bug in RawBencher broke chain compiled? From the changes I don't see what's changed in that area?

**Comment by Grauenwolf** [comment]
If you look at the last official test run, it says that Chain crashed. 

This appears to be caused by the binding redirects in app.config. Even though you have it set to automatically generate them in the project file, VS still likes to add them explicitly (and often incorrectly).

Just deleting that section in app.config allows it to work correctly.

**Comment by FransBouma** [comment]
Ah thanks, didn't know that.

**Comment by FransBouma** [comment]
Btw, there are now 9 Chain benchers in the set. That's a little much. Which ones aren't needed? Do there have to be compiled and non-compiled versions of ever bencher in the set?

**Comment by FransBouma** [comment]
Also, I think there's something wrong with the Chain change tracking bench code. It takes 5s or more per run, that's ... much slower than EF even, I think something's off, but haven't looked into it deeply. Are your results similar to that?

**Comment by Grauenwolf** [comment]
I can cut the number of benchmarks down tonight to just the most significant ones.

As for the change tracking, yea it's that bad. It demonstrates the use of internal dictionaries to back properties, a common MVVM technique. Probably all of the boxing is causing the problem.

**Comment by FransBouma** [comment]
> I can cut the number of benchmarks down tonight to just the most significant ones.

	Cool 😊 

> As for the change tracking, yea it's that bad. It demonstrates the use of internal dictionaries to
> back properties, a common MVVM technique. Probably all of the boxing is causing the problem.

	Hmm, not sure. I box all values too and change tracking fetches in llblgen is very fast. Perhaps a profile run will show more. It's so significant it looks like there's some bottleneck in there that's easy to solve. If I'm bored tomorrow I'll have a look.

**Comment by FransBouma** [comment]
Ah I see the problem :) 

It's rather simple. You use the public interface for materializing the entity object. That's not really a good choice. You should add a shortcut for materialization. For you that's rather simple: when materializing an object, you set a flag on the abstractmodelbase which sets a flag in the changetrackingpropertybag that it's being materialized. When this flag is set, it bypasses any checks (as these are useless anyway, the DB is the ground truth!) and events. It simply directly invokes the delegate for the setter. Almost all performance is lost in those setters with the checks/events. 

That should get you a huge performance jump. Additionally, a compiled expression which calls the actual property setter is faster, so you can build the expression tree once for a property, using the type and the propertyinfo, to call its setter, compile the expressiontree to an Action<> object and invoke that at runtime. Even faster might be to build a single expression that receives an IDataReader, where you simply create a new instance of the object and invoke each property by accessing e.g. reader.GetString(ordinalOfProperty) ... 

But the bypass of the internal processing is key to get this faster. It should be ok: what to do if a value from the db triggers an error or raises an event? (which aren't bound as the object is being materialized! )

**Comment by Grauenwolf** [comment]
Thanks for the suggestion. I'll look into doing that.

**Pull request merged**
